name: wake_up
description: "A melhor app de alarme do mundo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.4
  wakelock_plus: ^1.2.8
  sensors_plus: ^6.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  
  # --- O TRIO COMPATÍVEL ---
  alarm: 3.1.5         # A versão estável do alarme
  vibration: ^3.1.0    # Versão moderna da vibração (corrige o erro do Registrar)
  audioplayers: ^5.2.1 # Compatível com o alarm 3.1.5
  flutter_volume_controller: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alarm.mp3

# --- CONFIGURAÇÃO DO ÍCONE ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # A tua logo será usada como ícone
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A" # Fundo escuro para Androids novos
  adaptive_icon_foreground: "assets/icon.png"